version: '3'
services:
  wp:
    container_name: terraform
    image: hashicorp/terraform:0.14.7
    env_file:
      - .env
    volumes:
      - ./wordpress:/wordpress
    working_dir: /wordpress
    tty: true